name: Rust-CI

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.70
    - name: Build Debug
      run: cd lib && cargo build
  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.70
    - name: Build Release
      run: cd lib && cargo build --release --all-features
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.70
    - name: Run tests
      run: cd tests && cargo test && cd ../lib && cargo test
